export interface PaymentData {
    readonly amount: number
    readonly apply_num: string
    readonly bank_code?: number
    readonly bank_name?: string
    readonly buyer_addr?: string
    readonly buyer_email?: string
    readonly buyer_postcode?: string
    readonly buyer_tel?: string
    readonly buyer_name?: string
    readonly cancel_amount: number
    readonly cancel_history: any[]
    readonly cancel_reason?: string
    readonly cancel_receipt_urls: any[]
    readonly cancelled_at: number
    readonly card_code: any
    readonly card_name: any
    readonly card_number: any
    readonly card_quota: number
    readonly card_type: any
    readonly cash_receipt_issued: boolean
    readonly channel: string
    readonly currency: string
    readonly custom_data: any
    readonly imp_uid: string
    readonly merchant_uid: string
    readonly name: string
    readonly paid_at: number
    readonly pay_method: string
    readonly pg_id: string
    readonly pg_provider: string
    readonly pg_tid: string
    readonly status: string
}