name: "server-build-workflow"
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - run: npm run build
  notify-slack:
    needs: build
    name: Notify to slack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send slack when failed
        if: ${{ failure() }}
        uses: ./.github/actions/slack-notify
        with:
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
      - name: Send slack if success
        if: ${{ success() }}
        uses: ./.github/actions/slack-notify
        with:
          status: 성공
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
